In [2]:
import numpy as np
a = np.array([1,2,3,5])
a

array([1, 2, 3, 5])

In [6]:
b = np.zeros([5])
b

array([0., 0., 0., 0., 0.])

In [38]:
c = np.ones([5])
c.fill(9)
c

array([9., 9., 9., 9., 9.])

In [36]:
d= np.empty([5])
d

array([3., 3., 3., 3., 3.])

In [37]:
d.fill(3)
d

array([3., 3., 3., 3., 3.])

In [13]:
e = np.arange(5)
e

array([0, 1, 2, 3, 4])

In [15]:
e = np.arange(3,19)
e

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [17]:
f = np.arange(4,20,5)
f

array([ 4,  9, 14, 19])

In [21]:
g = np.linspace(0,15,num=5)
g

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

In [39]:
h = np.zeros([3,4])
h

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [40]:
h.fill(2)
h

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [29]:
h = np.ones([4,6])
h

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [33]:
i= np.arange(60).reshape(3,5, 4)
i

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

## Lecture 7b

In [42]:
food = np.array(["samosa", "pakora", "chatni"])
food

array(['samosa', 'pakora', 'chatni'], dtype='<U6')

In [44]:
prices = np.array([5,5,5])
prices

array([5, 5, 5])

In [45]:
type(prices)

numpy.ndarray

In [46]:
len(prices)

3

In [47]:
len(food)

3

In [51]:
prices[2]

5

In [52]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [53]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [54]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
#Specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [58]:
#Table of 5
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [60]:
#line space
np.linspace(2,10, num=8)

array([ 2.        ,  3.14285714,  4.28571429,  5.42857143,  6.57142857,
        7.71428571,  8.85714286, 10.        ])

In [67]:
#Specify data type
np.ones(50, dtype = np.float32)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
      dtype=float32)

## Array Functions

In [75]:
r = np.array([2,4,6,9,100,10.1,3, 12,987.4])
r

array([  2. ,   4. ,   6. ,   9. , 100. ,  10.1,   3. ,  12. , 987.4])

In [76]:
r.sort()
r

array([  2. ,   3. ,   4. ,   6. ,   9. ,  10.1,  12. , 100. , 987.4])

In [78]:
s = np.array([4,6,8,16])
np.concatenate((r,s))


array([  2. ,   3. ,   4. ,   6. ,   9. ,  10.1,  12. , 100. , 987.4,
         4. ,   6. ,   8. ,  16. ])

## 2D Array

In [96]:
y = np.array(([2,3,4,5], [6, 7, 8, 9]))
y

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [98]:
z = np.array(([2, 3, 4, 5], [12,13,14,15]))
z

array([[ 2,  3,  4,  5],
       [12, 13, 14, 15]])

In [99]:
np.concatenate((y,z))

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [ 2,  3,  4,  5],
       [12, 13, 14, 15]])

In [101]:
np.concatenate((y,z), axis =1)

array([[ 2,  3,  4,  5,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 12, 13, 14, 15]])